// Generated by CoffeeScript 1.4.0
var dojoConfig;

dojoConfig = {
  cacheBust: new Date(),
  has: {
    "dojo-firebug": true
  },
  basePath: "../",
  releaseDir: "./dist",
  baseUrl: "",
  tlmSiblingOfDojo: false,
  waitSeconds: 5,
  async: true,
  packages: [
    {
      name: "dojo",
      location: "lib/dojo"
    }, {
      name: "dijit",
      location: "lib/dijit"
    }, {
      name: "dojox",
      location: "lib/dojox"
    }, {
      name: "gojs",
      location: "gojs"
    }
  ]
};
